# Volumes - Kubernetes
# https://kubernetes.io/docs/concepts/storage/volumes/

# A portworxVolume is an elastic block storage layer that runs hyperconverged with Kubernetes. 
# Portworx fingerprints storage in a server, tiers based on capabilities, and aggregates capacity 
# across multiple servers. 

# Portworx runs in-guest in virtual machines or on bare metal Linux nodes.

apiVersion: v1
kind: Pod
metadata:
  name: test-portworx-volume-pod
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /mnt
      name: pxvol
  volumes:
  - name: pxvol
    # This Portworx volume must already exist.
    portworxVolume:
      volumeID: "pxvol"
      fsType: "<fs-type>"